#!/usr/bin/env bash
# Rebuild the scroll film from all clips in assets/clips (sorted by name):
# concat -> assets/film.mp4 -> assets/frames/f_XXXX.jpg -> js/manifest.js
set -euo pipefail
cd "$(dirname "$0")"
export PATH="/opt/homebrew/bin:$PATH"

FPS=12
W=1920 H=1080

CLIPS=(assets/clips/*.mp4)
N=${#CLIPS[@]}
INPUTS=()
FILTER=""
for i in "${!CLIPS[@]}"; do
  INPUTS+=(-i "${CLIPS[$i]}")
  FILTER+="[${i}:v]"
done
FILTER+="concat=n=${N}:v=1[v]"

echo "concatenating ${N} clips: ${CLIPS[*]}"
ffmpeg -y -v error "${INPUTS[@]}" \
  -filter_complex "${FILTER}" -map "[v]" \
  -c:v libx264 -crf 17 -preset medium -pix_fmt yuv420p assets/film.mp4

rm -f assets/frames/f_*.jpg
ffmpeg -y -v error -i assets/film.mp4 \
  -vf "fps=${FPS},scale=${W}:${H}:flags=lanczos,unsharp=5:5:0.35:5:5:0.0" \
  -q:v 3 assets/frames/f_%04d.jpg

COUNT=$(ls assets/frames/f_*.jpg | wc -l | tr -d ' ')
cat > js/manifest.js <<EOF
// generated by build_frames.sh — frame sequence descriptor
window.FRAME_MANIFEST = {
  count: ${COUNT},
  path: 'assets/frames/',
  prefix: 'f_',
  digits: 4,
  ext: '.jpg'
};
EOF

echo "film: $(ffprobe -v error -show_entries format=duration -of default=nw=1:nk=1 assets/film.mp4)s"
echo "frames: ${COUNT} ($(du -sh assets/frames | cut -f1))"
